networks:
  dalila-net:
    driver: bridge
    name: "dalila-net"

services:
  dalila-client-service:
    build:
      context: "."
      dockerfile: "./docker/dev/Dockerfile"
    container_name: "dalila-client-container"
    networks:
      - "dalila-net"
    ports:
      - "5000:5000"
    volumes:
      - ".:/client"
